# File: .github/workflows/manual-import.yml
name: "📥 Manual Historical Import"

on:
  workflow_dispatch:

jobs:
  historical-import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy requests gspread google-auth

      - name: Write Google credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_B64 }}" | base64 --decode > service_account.json

      - name: Validate credentials JSON
        run: |
          python - << 'EOF'
import json
with open('service_account.json') as f:
    json.load(f)
print('✅ service_account.json is valid JSON')
EOF


      - name: Run historical import
        run: |
          python monitor.py --historical
